import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="`{inter.className}` bg-gradient-to-b from-gray-300 to-gray-200">
        <Header />
        <main className="container">
          <div className="flex items-start justify-center min-h-screen">
            <div className="mt-20">{children}</div>
          </div>
        </main>
      </body>
    </html>
  )
}
